### ISSUE TITLE
Infografía |Conceptos y funciones de una librería o componentes y su aplicación en las Apps|

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/infografia-de-las-librerias-KarlaV0#2]
[TAP,U2,KarlaVO - Infografía Librerías.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-KarlaV0/files/6309862/TAP.U2.KarlaVO.-.Infografia.Librerias.pdf)

**Comment by Brisa-4** [comment]
[1. RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-KarlaV0/files/6366768/1.RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA.pdf)

**Comment by Brisa-4** [comment]
20/20
Calificó Brisa Osorio Ramírez

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
